[build]
  command = "CI=false && react-scripts build"
  commandOrigin = "config"
  functions = "netlify/functions"
  publish = "build"  # React apps typically output to the 'build' folder

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
